bill_of_materials/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.views import logout, login

# import  app.views import *
from app.views import IndexView, CreatePartView, PartListView, PartDetailView, CreateSubAssemblyView, SubAssemblyListView, SubAssemblyDetailView
from app.views import CreateAssemblyView, AssemblyListView, AssemblyDetailView, CreateCustomerView, CustomerListView, CreateSupplierView, SupplierListView
from app.views import CreateProjectView, ProjectListView, ProjectDetailView, CustomerDetailView, SupplierDetailView, CreateSubCategoryView, CreateCategoryView
from app.views import CategoryListView, SubCategoryListView, HighriseView, CreateUserView, ProfilePageView, CreateFinishView, FinishListView, FinishDetailView
from app.views import CreatePlatingView, PlatingListView, PlatingDetailView, AboutView



urlpatterns = [
    path('admin', admin.site.urls),
    # path(r'^', include('django.contrib.auth.paths')),
    path('', IndexView.as_view(), name="index_view"),
    path('highrise/', HighriseView.as_view(), name="highrise_view"),
    path('about', AboutView.as_view(), name="about_view"),
    path('create_user', CreateUserView.as_view(), name="create_user"),
    path('accounts/profile', login_required(ProfilePageView), name="profile_page_view"),
    path('create_category', login_required(CreateCategoryView), name="create_category_view"),
    path('category_list', login_required(CategoryListView), name="category_list_view"),
    path('create_subcategory', login_required(CreateSubCategoryView), name="create_subcategory_view"),
    path('subcategory_list', login_required(SubCategoryListView), name="subcategory_list_view"),
    path('create_part', login_required(CreatePartView), name="create_part_view"),
    path('part_list', login_required(PartListView), name="part_list_view"),
    path('part_list/(?P<pk>\d+)', login_required(PartDetailView), name="part_detail_view"),
    path('create_subassembly', login_required(CreateSubAssemblyView), name="create_subassembly_view"),
    path('subassembly_list', login_required(SubAssemblyListView), name="subassembly_list_view"),
    path('subassembly_list/(?P<pk>\d+)', login_required(SubAssemblyDetailView), name="subassembly_detail_view"),
    path('create_assembly', login_required(CreateAssemblyView), name="create_assembly_view"),
    path('assembly_list', login_required(AssemblyListView), name="assembly_list_view"),
    path('assembly_list/(?P<pk>\d+)', login_required(AssemblyDetailView), name="assembly_detail_view"),
    path('create_customer', login_required(CreateCustomerView), name="create_customer_view"),
    path('customer_list', login_required(CustomerListView), name="customer_list_view"),
    path('customer_list/(?P<pk>\d+)', login_required(CustomerDetailView), name="customer_detail_view"),
    path('create_supplier', login_required(CreateSupplierView), name="create_supplier_view"),
    path('supplier_list', login_required(SupplierListView) , name="supplier_list_view"),
    path('supplier_list/(?P<pk>\d+)', login_required(SupplierDetailView), name="supplier_detail_view"),
    path('create_project', login_required(CreateProjectView), name="create_project_view"),
    path('project_list', login_required(ProjectListView), name="project_list_view"),
    path('project_list/(?P<pk>\d+)', login_required(ProjectDetailView), name="project_detail_view"),
    path('create_finish', login_required(CreateFinishView), name="create_finish_view"),
    path('finish_list', login_required(FinishListView) , name="finish_list_view"),
    path('finish_list/(?P<pk>\d+)', login_required(FinishDetailView), name="finish_detail_view"),
    path('create_plating', login_required(CreatePlatingView), name="create_plating_view"),
    path('plating_list', login_required(PlatingListView) , name="plating_list_view"),
    path('plating_list/(?P<pk>\d+)', login_required(PlatingDetailView), name="plating_detail_view")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class Category(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    category = models.CharField(max_length=30)

    def __str__(self):
        return self.category


class SubCategory(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.CharField(max_length=30)

    def __str__(self):
        return self.subcategory


class ShippingTerms(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    shipping_type = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    preferred_shipper = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.shipping_type


class Part(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    part_name = models.CharField(max_length=50)
    part_number = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=50, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey('app.Supplier', null=True, blank=True, on_delete=models.CASCADE)
    manufacturer_pn = models.CharField(max_length=50, null=True, blank=True)
    dimensions = models.CharField(max_length=50, null=True, blank=True)
    finish = models.ForeignKey('app.FinishTable', null=True, blank=True, on_delete=models.CASCADE)
    plating = models.ForeignKey('app.PlatingTable', null=True, blank=True, on_delete=models.CASCADE)
    uom = models.CharField(max_length=15, null=True, blank=True)
    unit_cost = models.DecimalField(max_digits=10, decimal_places=2)
    part_url = models.URLField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    cad_file = models.FileField(upload_to="cad_files", null=True, blank=True)
    image = models.ImageField(upload_to="image_files", null=True, blank=True, verbose_name="Part Image")

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return "https://cdn3.iconfinder.com/data/icons/smoothfill-action/30/action_088-no_camera-capture-picture-image-photo-128.png"

    def __str__(self):
        return self.part_name


class SubAssemblyQuantity(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    assembly = models.ForeignKey('app.SubAssembly', on_delete=models.CASCADE)

    @property
    def cost(self):
        cost = self.part.unit_cost * self.quantity
        return cost

    def __str__(self):
        return self.part.part_name


class AssemblyQuantity(models.Model):
    part = models.ForeignKey(Part, null=True, blank=True, on_delete=models.CASCADE)
    subassembly = models.ForeignKey('app.SubAssembly', null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    assembly = models.ForeignKey('app.Assembly', null=True, blank=True, on_delete=models.CASCADE)

    @property
    def sub_cost(self):
        if not self.part:
            return 0
        cost = self.part.unit_cost * self.quantity
        return cost

    @property
    def cost(self):
        if not self.part:
            return 0
        cost = self.part.unit_cost * self.quantity
        return cost

    def __str__(self):
        return self.assembly.assembly_name


class SubAssembly(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    sub_assembly_name = models.CharField(max_length=50)
    sub_assembly_number = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=50, null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, null=True, blank=True, on_delete=models.CASCADE)
    mfg_supplier = models.ForeignKey('app.Supplier', null=True, blank=True, on_delete=models.CASCADE)
    mfg_supplier_pn = models.CharField(max_length=50, null=True, blank=True)
    finish = models.ForeignKey('app.FinishTable', null=True, blank=True, on_delete=models.CASCADE)
    plating = models.ForeignKey('app.PlatingTable', null=True, blank=True, on_delete=models.CASCADE)
    subassembly_cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    cad_file = models.FileField(upload_to="cad_files", null=True, blank=True)
    image = models.ImageField(upload_to="image_files", null=True, blank=True, verbose_name="Part Image")

    @property
    def cost(self):
        cost = 0
        for subassemblyquantity in self.subassemblyquantity_set.all():
            cost += subassemblyquantity.cost
        return cost

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return "https://cdn3.iconfinder.com/data/icons/smoothfill-action/30/action_088-no_camera-capture-picture-image-photo-128.png"

    def __str__(self):
        return self.sub_assembly_name


class Assembly(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    assembly_name = models.CharField(max_length=50)
    assembly_part_number = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=50, null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(SubCategory, null=True, blank=True, on_delete=models.CASCADE)
    supplier = models.ForeignKey('app.Supplier', null=True, blank=True, on_delete=models.CASCADE)
    supplier_pn = models.CharField(max_length=50, null=True, blank=True)
    finish = models.ForeignKey('app.FinishTable', null=True, blank=True, on_delete=models.CASCADE)
    plating = models.ForeignKey('app.PlatingTable', null=True, blank=True, on_delete=models.CASCADE)
    assembly_cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    cad_file = models.FileField(upload_to="cad_files", null=True, blank=True)
    image = models.ImageField(upload_to="image_files", null=True, blank=True, verbose_name="Part Image")

    @property
    def cost(self):
        cost = 0
        for assembly_quantity in self.assemblyquantity_set.all():
            cost += assembly_quantity.cost
            subassembly = assembly_quantity.subassembly
            if subassembly:
                cost += subassembly.cost * assembly_quantity.quantity
        return cost

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return "https://cdn3.iconfinder.com/data/icons/smoothfill-action/30/action_088-no_camera-capture-picture-image-photo-128.png"

    def __str__(self):
        return self.assembly_name


class ProjectQuantity(models.Model):
    assembly = models.ForeignKey('app.Assembly', null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price_per_assembly = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    project = models.ForeignKey('app.Project', null=True, blank=True, on_delete=models.CASCADE)


class Project(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    project_number = models.AutoField(primary_key=True)
    client = models.ForeignKey('app.Customer', on_delete=models.CASCADE)
    project_name = models.CharField(max_length=50)
    price_per_project = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    shipping_address = models.TextField(null=True, blank=True)
    shipping_terms = models.ForeignKey(ShippingTerms, null=True, blank=True, on_delete=models.CASCADE)
    expected_delivery = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.project_name


class Customer(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    title = models.CharField(max_length=30, null=True, blank=True)
    company_name = models.CharField(max_length=25, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    email_address = models.CharField(max_length=60, null=True, blank=True)
    twitter_account = models.CharField(max_length=25, null=True, blank=True)
    web_address = models.URLField(null=True, blank=True)
    street_address = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=2, null=True, blank=True)
    zip_code = models.IntegerField(null=True, blank=True)
    country = models.CharField(max_length=25, null=True, blank=True)

    def __str__(self):
        return self.company_name


class Supplier(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    title = models.CharField(max_length=30)
    company_name = models.CharField(max_length=25, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    email_address = models.CharField(max_length=60, null=True, blank=True)
    twitter_account = models.CharField(max_length=25, null=True, blank=True)
    web_address = models.URLField(null=True, blank=True)

templates/app/assembly_form.html
{% extends "bom.html" %}
{% load bootstrap %}
{% load static %}

{% block content %}
    <div class="row">
<div class="container">
  <div class="row">
    <div class="col-lg-5">
  <form id="myForm" method="post" action="" enctype="multipart/form-data">
    <legend>Create An Assembly</legend>
      {% csrf_token %}
        {{ form|bootstrap }}
        <table border="0" cellpadding="0" cellspacing="0">
            <tbody>
              {% for inline in inlines %}
                {{inline.management_form}}
                  {% for form in inline.forms %}
                      <tr>
                        <td>{{form|bootstrap}}</td>
                        <td>{% if inline.instance.pk %}{{ inline.DELETE }}{% endif %}</td>
                      </tr>
                  {% endfor %}
              {% endfor %}
            </tbody>
        </table>
      <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Create Assembly"></input>
      </div>
  </form>
</div>
</div>
</div>


{% endblock %}

{% block extrascript %}
<script type="text/javascript" src="{% static 'app/src/jquery.formset.js' %}"></script>

<script type="text/javascript">
$(function() {

    {% for formset in inlines %}
      $('#myForm tbody tr').formset({
          prefix: '{{ formset.prefix }}',
          formCssClass: 'dynamic-formset{{ forloop.counter }}'
      });
    {% endfor %}

})
</script>
{% endblock %}

templates/app/category_form.html
{% extends "bom.html" %}
{% load bootstrap %}


{% block content %}
<div class="row">
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <form role="form" method="post">
        <legend>Create A New Category</legend>
          {% csrf_token %}
            {{ form|bootstrap }}
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create Category"></input>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/app/customer_form.html
{% extends "base.html" %}
{% load bootstrap %}


{% block content %}
<div class="row">
  <nav>
    <div class="col-md-2">
      <a href="{% url 'create_customer_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Customer</small></a>
      <a href="{% url 'customer_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Customer Listing</small></a>
      <a href="{% url 'create_supplier_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Supplier</small></a>
      <a href="{% url 'supplier_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Supplier Listing</small></a>
      <a href="{% url 'create_part_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Part</small></a>
      <a href="{% url 'part_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Part Listing</small></a>
      <a href="{% url 'create_subassembly_view' %}" type="button" class="btn btn-primary btn-block"><small>Create SubAssmbly</small></a>
      <a href="{% url 'subassembly_list_view' %}" type="button" class="btn btn-primary btn-block"><small>SubAssembly Listing</small></a>
      <a href="{% url 'create_assembly_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Assembly</small></a>
      <a href="{% url 'assembly_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Assembly Listing</small></a>
      <a href="{% url 'create_project_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Project</small></a>
      <a href="{% url 'project_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Project Listing</small></a>
    </div>
  </nav>
  <div class="col-md-9">
    <div class="row">
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <form role="form" method="post">
        <legend>Create A New Customer</legend>
          {% csrf_token %}
            {{ form|bootstrap }}
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create Customer"></input>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/app/finishtable_detail.html
{% extends "bom.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12 well">
    <h4>{{object.finish}}  |  <small>Part ID: </small>{{object.pk}}<img class="thumbnail pull-right" height="250px" width="250px" src="{{object.image_url}}" alt="{{object.finish}}"/></h4>
    <h4><small>Description </small>{{object.description}}</h4>
    <h4><small>Source: </small>{{object.source}}</h4>
  </div>
{% endblock %}

templates/app/platingtable_detail.html
{% extends "bom.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12 well">
    <h3>{{object.plating}}  |  <small>Part ID: </small>{{object.pk}}
    <h3><small>Description </small>{{object.description}}</h3>
    <h3><small>Source: </small>{{object.source}}</h3>
  </div>
{% endblock %}

templates/app/platingtable_list.html
{% extends "bom.html" %}


{% block content %}
  <div class="row">
    <div class="col-md-12 well well-lg">
      <h3 class="pull-left">Plating Listing</h3>
    </div>
    {% for object in object_list %}
      <div class="col-md-12 well well-sm">
        <h4>{{object.plating}}  |  <small>Description: </small>{{object.description}}  |  <small>Source: </small>{{object.source}}<a class="btn btn-primary pull-right" type="button" name="drilldown" href="{% url 'plating_detail_view' object.pk %}">Details</a></h4>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/app/project_form.html
{% extends "bom.html" %}
{% load bootstrap %}
{% load static %}

{% block content %}
    <div class="row">
<div class="container">
  <div class="row">
    <div class="col-lg-5">
  <form id="myForm" method="post" action="">
            <legend>Create A Project</legend>
            {% csrf_token %}
              {{ form|bootstrap }}
        <table border="0" cellpadding="0" cellspacing="0">
            <tbody>
              {% for inline in inlines %}
              {{inline.management_form}}
                {% for form in inline.forms %}
              <tr>
                <td>{{form|bootstrap}}</td>
                 <td>{% if inline.instance.pk %}{{ inline.DELETE }}{% endif %}</td>
              </tr>
              {% endfor %}

              {% endfor %}
          </tbody>
      </table>
      <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Create Project"></input>
      </div>
  </form>
</div>
</div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript" src="{% static 'app/src/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $(function() {

        {% for formset in inlines %}
          $('#myForm tbody tr').formset({
              prefix: '{{ formset.prefix }}',
              formCssClass: 'dynamic-formset{{ forloop.counter }}'
          });
        {% endfor %}

    })
</script>

{% endblock %}

templates/app/project_list.html
{% extends "bom.html" %}

{% block content %}
{% for object in object_list %}
<div class="row">
  <div class="col-md-12 well">
    <h3>{{object.project_name}}</h3>
  </div>
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th><small>Project ID</small></th>
        <th><small>Project Number</small></th>
        <th><small>Client</small></th>
        <th><small>Project Name</small></th>
        <th><small>Project Price</small></th>
      </tr>
      <tr>
        <td><small>{{object.pk}}</small></td>
        <td><small>{{object.project_number}}</small></td>
        <td><small>{{object.client}}</small></td>
        <td><small>{{object.project_name}}</small></td>
        <td><small>$ {{object.price_per_project}}</small></td>
      </tr>
    </table>
    </div>
  <div class="row">
    <div class="col-md-12 page-header">
      <h3><small>Items Ordered:</small></h3>
    </div>
  </div>
  <div>
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th><small>Part ID</small></th>
      <th><small>Assembly Name</small></th>
      <th><small>Assembly Number</small></th>
      <th><small>Description</small></th>
      <th><small>Category</small></th>
      <th><small>Sub Category</small></th>
      <th><small>Supplier</small></th>
      <th><small>Supplier PN</small></th>
      <th><small>Finish</small></th>
      <th><small>Plating</small></th>
      <th><small>Quantity</small></th>
      <th><small>Cost/Assembly</small></th>
    </tr>
    {% for assembly in object.projectquantity_set.all %}
    <tr>
      <td><a href="{% url 'assembly_detail_view' assembly.assembly.pk %}"><small>{{assembly.assembly.pk}}</small></a></td>
      <td><small>{{assembly.assembly.assembly_name}}</small></td>
      <td><small>{{assembly.assembly.assembly_part_number}}</small></td>
      <td><small>{{assembly.assembly.description}}</small></td>
      <td><small>{{assembly.assembly.category}}</small></td>
      <td><small>{{assembly.assembly.sub_category}}</small></td>
      <td><small>{{assembly.assembly.supplier}}</small></td>
      <td><small>{{assembly.assembly.supplier_pn}}</small></td>
      <td><small>{{assembly.assembly.finish}}</small></td>
      <td><small>{{assembly.assembly.plating}}</small></td>
      <td><small>{{assembly.quantity}}</small></td>
      <td><small>$ {{assembly.assembly.cost}}</small></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endfor %}
{% endblock %}

templates/app/subassemblyquantity_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
<nav>
    <div class="col-md-2">
      <a href="{% url 'create_customer_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Customer</small></a>
      <a href="{% url 'customer_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Customer Listing</small></a>
      <a href="{% url 'create_supplier_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Supplier</small></a>
      <a href="{% url 'supplier_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Supplier Listing</small></a>
      <a href="{% url 'create_part_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Part</small></a>
      <a href="{% url 'part_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Part Listing</small></a>
      <a href="{% url 'create_subassembly_view' %}" type="button" class="btn btn-primary btn-block"><small>Create SubAssmbly</small></a>
      <a href="{% url 'subassembly_list_view' %}" type="button" class="btn btn-primary btn-block"><small>SubAssembly Listing</small></a>
      <a href="{% url 'create_assembly_view' %}" type="button" class="btn btn-primary btn-block"><small>Create Assembly</small></a>
      <a href="{% url 'assembly_list_view' %}" type="button" class="btn btn-primary btn-block"><small>Assembly Listing</small></a>
    </div>
</nav>
  <div class="col-md-9">
{% for object in object_list %}
  <div class="row">
    <div class="col-md-12 well">
      <h2>SubAssembly Id: {{object.id}}  :  {{object.sub_assembly_name}}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tr>
          <th><small>Part Id</small></th>
          <th><small>Part Name</small></th>
          <th><small>Part Number</small></th>
          <th><small>Description</small></th>
          <th><small>Category</small></th>
          <th><small>Sub Category</small></th>
          <th><small>Manufacturer</small></th>
          <th><small>Manufacturer PN</small></th>
          <th><small>Dimensions</small></th>
          <th><small>Finish</small></th>
          <th><small>Plating</small></th>
          <th><small>Qty</small></th>
          <th><small>UoM</small></th>
          <th><small>Cost/Unit</small></th>
          <th><small>Extended Cost</small></th>

        </tr>
        {% for part in object.subassemblyquantity_set.all %}
          <tr>
          <td><small>{{part.part.pk}}</small></td>
          <td><small>{{part.part.part_name}}</small></td>
          <td><small>{{part.part.part_number}}</small></td>
          <td><small>{{part.part.description}}</small></td>
          <td><small>{{part.part.category}}</small></td>
          <td><small>{{part.part.sub_category}}</small></td>
          <td><small>{{part.part.manufacturer}}</small></td>
          <td><small>{{part.part.manufacturer_pn}}</small></td>
          <td><small>{{part.part.dimensions}}</small></td>
          <td><small>{{part.part.finish}}</small></td>
          <td><small>{{part.part.plating}}</small></td>
          <td><small>{{part.quantity}}</small></td>
          <td><small>{{part.part.uom}}</small></td>
          <td><small>{{part.part.unit_cost}}</small></td>
          <td><small></small></td>
          </tr>
          {% endfor %}
      </table>
    </div>
  {% endfor %}
</div>
</div>
{% endblock %}

templates/app/subcategory_form.html
{% extends "bom.html" %}
{% load bootstrap %}


{% block content %}
    <div class="row">
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <form role="form" method="post">
        <legend>Create A New SubCategory</legend>
          {% csrf_token %}
            {{ form|bootstrap }}
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create SubCategory"></input>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/app/subcategory_list.html
{% extends "bom.html" %}

{% block content %}

      <div class="row">
        <div class="col-md-12 well well-lg">
          <h3 class="pull-left">Sub Category Listing</h3>
          </div>
        {% for object in object_list %}
            <div class="col-md-12 well well-sm">
              <h4><small>Category: </small>{{object.category}}  |  <small>Sub Category: </small>{{object.subcategory}}<a class="btn btn-success pull-right" type="button" name="drilldown" href="{% url 'create_category_view' %}">Update Sub Category Information</a></h4>
            </div>
        {% endfor %}
  </div>
</div>
{% endblock %}

templates/app/userprofile_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <form class="" action="" method="post">
        {% csrf_token %}
          {{form|bootstrap}}
        <input class="btn btn-success" type="submit" name="newuser" value="Create User!">
      </form>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}